// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1c5cf486-cfbc-4f2c-9474-97ab04b84207",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_uS6S65Unp",
    "aws_user_pools_web_client_id": "5v5g0nc1ki302gsmrju6ug2j8q",
    "oauth": {}
};


export default awsmobile;
